- app/controllers/waiver_infos_controller.rb
- spec/requests/waiver_infos_controller_spec.rb
> Implementing support for Account authorization for accessing WaiverInfo

- spec/factories/employees.rb
- spec/spec_helper.rb
> Ensure uniqueness of netid in factory

- app/assets/stylesheets/application.scss
- app/views/layouts/application.html.erb
- config/initializers/git_sha.rb
> Display version info in application footer

- app/controllers/accounts_controller.rb
- app/models/account.rb
- config/routes.rb
- spec/routing/accounts_routing_spec.rb
> Fixing the "Not found. Authentication passthru." devise bug

- package.json
Addresses https://github.com/pulibrary/oawaiver/security/dependabot/2
> Upgrade glob_parent to address security issue

- package.json
- yarn.lock
- [Fixing webpack-dev-server in response to](https://github.com/pulibrary/oawaiver/commit/d27c3f3d1343bedfcb7ccafd8b436010b2ac579e) https://github.com/rails/rails/issues/43062
- [Adding the following Babel dependencies for the package.json: "@babel/plugin-proposal-private-methods": "^7.18.6", "@babel/plugin-proposal-private-property-in-object": "^7.21.11"](https://github.com/pulibrary/oawaiver/commit/0444e3dbfa06cceffdf703cd502c33c88b9f289e)
> Fixing webpack-dev-server in response to rails/rails#43062

- config/deploy/production.rb
related to https://github.com/pulibrary/princeton_ansible/issues/3476
> add jammy vm

- Gemfile
- Gemfile.lock
> Removing sprockets and modernizr-rails as dependencies

- Gemfile.lock
This addresses https://github.com/pulibrary/oawaiver/pull/124#issuecomment-1884968409
> Ensuring that the ActiveStorage configuration file is tracked (this is required for Capistrano deployments)

- README.md
> add coveralls badge

- .circleci/config.yml
- spec/rails_helper.rb
- spec/spec_helper.rb
This should ensure that Coveralls is properly generating test coverage metrics.
> Ensuring that the Coveralls integration properly analyzes the code coverage metrics

- Gemfile
- Gemfile.lock
- spec/rails_helper.rb
> Restores Coveralls reporting

- app/services/waiver_info_report.rb
- lib/tasks/account.rake
- lib/tasks/report.rake
- spec/services/waiver_info_report_spec.rb
> Implementing the WaiverInfoReport class in order to generate CSV reports for WaiverInfo attributes

- package.json
- yarn.lock
Addresses https://github.com/pulibrary/oawaiver/security/dependabot/142
> Updating the `cookie` package dependency to 0.7.0 or later releases

- yarn.lock
> Upgrade yarn dependencies to unblock security patch

- config/deploy/production.rb
> Add prod1 back to deploy

- .circleci/config.yml
- .tool-versions
- README.md
> Upgrading Node.js to release 22.13.1 (LTS Jod)

- package.json
This resolves https://github.com/pulibrary/oawaiver/security/dependabot/159
> Upgrading esbuilt to release 0.21.3

- package.json
Resolves https://github.com/pulibrary/oawaiver/security/dependabot/159
> Upgrading esbuild to 0.25.1

- package.json
- yarn.lock
Resolves https://github.com/pulibrary/oawaiver/security/dependabot/159
> Upgrading vite to release 6.0.15
